apiVersion: batch/v1
kind: Job
metadata:
  name: v0.14.0-upgrade
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.14.2"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: eventing-controller
      restartPolicy: Never
      containers:
      - name: upgrade-brokers
        image: gcr.io/knative-releases/knative.dev/eventing/cmd/upgrade/v0.14.0@sha256:8ad31868892f8730c818f23f45ea2fce278a37bc609954870f28f0bbfe3934ee

---
